version: '3.3'

services:

  api-dev:
    container_name: api-dev
    image: api-dev
    build:
      context: ./api
      dockerfile: Dockerfile_dev
  
  nginx-hello:
    container_name: nginx-hello
    image: nginx-hello
    build:
      context: ./hello
      dockerfile: Dockerfile_dev
    ports:
      - 8080:80
    depends_on:
      - api-dev  
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/nginx-dev/var/log/nginx:/var/log/nginx
    