FROM node:8.15.0-alpine
#COPY package.json package-lock.json ./
#RUN npm set progress=false && npm config set depth 0 && npm cache clean --force
#RUN npm chache clean
#RUN npm i && mkdir /ng-app && cp -R ./node_modules ./ng-app
WORKDIR /ng-app
COPY . .
RUN $(npm bin)/ng build --prod

FROM nginx:stable-alpine
COPY --from=0 /ng-app/dist /usr/share/nginx/html